#!/usr/bin/env python3
"""
generate_base_pack.py — Genera data/seed/base_pack.json con todos los datos
de app/js/words.js enriquecidos con difficulty, similarity y tier.
"""

import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, "data", "seed", "base_pack.json")

# ── Datos extraídos de app/js/words.js + enriquecidos ──────
# difficulty: 1=muy difícil/rara, 5=muy fácil/común
# similarity: 0.50-1.00, tier: A(0.85+), B(0.70-0.84), C(0.50-0.69)

CATEGORIES = [
    {
        "id": "animals",
        "name": "Animales",
        "icon_emoji": "🐾",
        "is_premium": False,
        "sort_order": 1,
    },
    {
        "id": "food",
        "name": "Comida y Bebida",
        "icon_emoji": "🍕",
        "is_premium": False,
        "sort_order": 2,
    },
    {
        "id": "sports",
        "name": "Deportes",
        "icon_emoji": "⚽",
        "is_premium": False,
        "sort_order": 3,
    },
    {
        "id": "places",
        "name": "Países y Ciudades",
        "icon_emoji": "🌍",
        "is_premium": False,
        "sort_order": 4,
    },
    {
        "id": "movies",
        "name": "Cine y TV",
        "icon_emoji": "🎬",
        "is_premium": False,
        "sort_order": 5,
    },
    {
        "id": "music",
        "name": "Música",
        "icon_emoji": "🎵",
        "is_premium": False,
        "sort_order": 6,
    },
    {
        "id": "science",
        "name": "Ciencia y Tecnología",
        "icon_emoji": "🧪",
        "is_premium": True,
        "sort_order": 7,
    },
    {
        "id": "emotions",
        "name": "Emociones",
        "icon_emoji": "🎭",
        "is_premium": True,
        "sort_order": 8,
    },
]

# Words: (text, category_id, difficulty)
WORDS_DATA = {
    "animals": [
        ("Perro", 5),
        ("Gato", 5),
        ("León", 5),
        ("Águila", 4),
        ("Tiburón", 4),
        ("Elefante", 5),
        ("Serpiente", 4),
        ("Caballo", 5),
        ("Oso", 5),
        ("Mono", 5),
        ("Conejo", 5),
        ("Ballena", 4),
        ("Pingüino", 4),
        ("Tortuga", 5),
        ("Loro", 4),
        ("Araña", 4),
        ("Mariposa", 4),
        ("Ciervo", 3),
        ("Ratón", 5),
        ("Jirafa", 4),
        # Pair-only words that need to exist in the DB
        ("Lobo", 4),
        ("Zorro", 4),
        ("Pantera", 3),
        ("Lince", 2),
        ("Tigre", 5),
        ("Puma", 3),
        ("Leopardo", 3),
        ("Halcón", 3),
        ("Búho", 4),
        ("Cóndor", 2),
        ("Delfín", 5),
        ("Orca", 3),
        ("Rinoceronte", 3),
        ("Hipopótamo", 3),
        ("Mamut", 2),
        ("Lagarto", 3),
        ("Cocodrilo", 4),
        ("Iguana", 3),
        ("Burro", 4),
        ("Cebra", 4),
        ("Poni", 3),
        ("Panda", 4),
        ("Koala", 4),
        ("Mapache", 3),
        ("Gorila", 4),
        ("Chimpancé", 3),
        ("Orangután", 2),
        ("Liebre", 3),
        ("Hámster", 4),
        ("Foca", 3),
        ("Gaviota", 4),
        ("Albatros", 2),
        ("Caracol", 4),
        ("Cangrejo", 4),
        ("Tucán", 3),
        ("Guacamayo", 2),
        ("Canario", 4),
        ("Escorpión", 3),
        ("Hormiga", 4),
        ("Escarabajo", 3),
        ("Libélula", 3),
        ("Abeja", 4),
        ("Polilla", 3),
        ("Alce", 2),
        ("Reno", 3),
        ("Gacela", 2),
        ("Rata", 4),
        ("Ardilla", 4),
        ("Avestruz", 3),
        ("Camello", 3),
        ("Llama", 3),
        ("Morsa", 2),
    ],
    "food": [
        ("Pizza", 5),
        ("Hamburguesa", 5),
        ("Sushi", 4),
        ("Paella", 4),
        ("Chocolate", 5),
        ("Café", 5),
        ("Cerveza", 5),
        ("Helado", 5),
        ("Tortilla", 5),
        ("Croissant", 4),
        ("Taco", 4),
        ("Pasta", 5),
        ("Ensalada", 5),
        ("Manzana", 5),
        ("Queso", 5),
        ("Pan", 5),
        ("Limonada", 4),
        ("Fresa", 5),
        ("Pollo", 5),
        ("Sopa", 5),
        # Pair-only words
        ("Calzone", 2),
        ("Focaccia", 2),
        ("Empanada", 4),
        ("Hot Dog", 4),
        ("Sándwich", 5),
        ("Kebab", 3),
        ("Sashimi", 2),
        ("Tempura", 3),
        ("Ramen", 3),
        ("Risotto", 3),
        ("Arroz frito", 4),
        ("Fideuá", 3),
        ("Cacao", 3),
        ("Brownie", 4),
        ("Turrón", 3),
        ("Té", 5),
        ("Capuchino", 4),
        ("Espresso", 3),
        ("Sidra", 3),
        ("Vino", 5),
        ("Sorbete", 3),
        ("Granizado", 4),
        ("Natillas", 4),
        ("Omelette", 3),
        ("Frittata", 2),
        ("Revuelto", 4),
        ("Donut", 4),
        ("Magdalena", 4),
        ("Churro", 4),
        ("Burrito", 4),
        ("Quesadilla", 3),
        ("Enchilada", 3),
        ("Fideos", 4),
        ("Lasaña", 4),
        ("Macarrones", 5),
        ("Gazpacho", 3),
        ("Ceviche", 3),
        ("Carpaccio", 2),
        ("Pera", 5),
        ("Melocotón", 4),
        ("Ciruela", 4),
        ("Mantequilla", 4),
        ("Yogur", 5),
        ("Nata", 4),
        ("Galleta", 5),
        ("Tostada", 5),
        ("Arepa", 3),
        ("Naranjada", 3),
        ("Zumo", 5),
        ("Horchata", 3),
        ("Frambuesa", 3),
        ("Cereza", 4),
        ("Mora", 4),
        ("Pavo", 4),
        ("Pato", 4),
        ("Codorniz", 2),
        ("Caldo", 4),
        ("Crema", 4),
        ("Guiso", 4),
    ],
    "sports": [
        ("Fútbol", 5),
        ("Baloncesto", 5),
        ("Tenis", 5),
        ("Natación", 5),
        ("Ciclismo", 4),
        ("Boxeo", 4),
        ("Golf", 4),
        ("Atletismo", 4),
        ("Esquí", 4),
        ("Surf", 4),
        ("Béisbol", 4),
        ("Escalada", 3),
        ("Gimnasia", 4),
        ("Esgrima", 2),
        ("Ajedrez", 4),
        ("Fórmula 1", 4),
        ("Skate", 4),
        ("Polo", 2),
        ("Rugby", 4),
        ("Vela", 3),
        # Pair-only words
        ("Fútbol sala", 3),
        ("Hockey", 4),
        ("Voleibol", 4),
        ("Balonmano", 3),
        ("Netball", 1),
        ("Bádminton", 3),
        ("Pádel", 4),
        ("Ping-pong", 4),
        ("Waterpolo", 3),
        ("Buceo", 3),
        ("Patinaje", 4),
        ("Monopatín", 4),
        ("BMX", 3),
        ("Karate", 4),
        ("Judo", 3),
        ("Lucha libre", 3),
        ("Billar", 4),
        ("Croquet", 2),
        ("Bolos", 4),
        ("Maratón", 4),
        ("Triatlón", 3),
        ("Cross", 3),
        ("Snowboard", 4),
        ("Patinaje hielo", 3),
        ("Trineo", 3),
        ("Windsurf", 3),
        ("Kayak", 3),
        ("Bodyboard", 2),
        ("Softball", 2),
        ("Cricket", 3),
        ("Rounders", 1),
        ("Senderismo", 4),
        ("Rappel", 3),
        ("Espeleología", 2),
        ("Yoga", 4),
        ("Pilates", 4),
        ("Danza", 4),
        ("Tiro con arco", 3),
        ("Lanzamiento", 3),
        ("Jabalina", 3),
        ("Damas", 4),
        ("Go", 3),
        ("Backgammon", 2),
        ("Rally", 3),
        ("NASCAR", 3),
        ("MotoGP", 3),
        ("Scooter", 3),
        ("Roller", 3),
        ("Longboard", 2),
        ("Equitación", 3),
        ("Hípica", 2),
        ("Rodeo", 3),
        ("Fútbol americano", 4),
        ("Lacrosse", 2),
        ("Hurling", 1),
        ("Remo", 3),
        ("Piragüismo", 3),
        ("Canoa", 3),
    ],
    "places": [
        ("París", 5),
        ("Tokio", 5),
        ("Nueva York", 5),
        ("España", 5),
        ("Brasil", 5),
        ("Egipto", 4),
        ("Australia", 5),
        ("Moscú", 4),
        ("Amazonas", 4),
        ("Sahara", 3),
        ("Alpes", 3),
        ("Hawái", 4),
        ("Venecia", 4),
        ("Cuba", 4),
        ("India", 5),
        ("Roma", 5),
        ("Dubái", 4),
        ("Japón", 5),
        ("Alaska", 3),
        ("Hollywood", 4),
        # Pair-only words
        ("Londres", 5),
        ("Berlín", 4),
        ("Seúl", 3),
        ("Pekín", 4),
        ("Osaka", 3),
        ("Chicago", 4),
        ("Los Ángeles", 5),
        ("Toronto", 4),
        ("Portugal", 4),
        ("Italia", 5),
        ("Francia", 5),
        ("Argentina", 5),
        ("Colombia", 4),
        ("México", 5),
        ("Marruecos", 3),
        ("Turquía", 4),
        ("Grecia", 4),
        ("Nueva Zelanda", 3),
        ("Canadá", 5),
        ("Sudáfrica", 3),
        ("San Petersburgo", 2),
        ("Varsovia", 3),
        ("Praga", 3),
        ("Nilo", 3),
        ("Misisipi", 3),
        ("Ganges", 3),
        ("Gobi", 2),
        ("Atacama", 2),
        ("Kalahari", 2),
        ("Andes", 3),
        ("Himalaya", 3),
        ("Pirineos", 3),
        ("Bali", 3),
        ("Maldivas", 3),
        ("Canarias", 4),
        ("Ámsterdam", 4),
        ("Brujas", 3),
        ("Estocolmo", 3),
        ("Jamaica", 4),
        ("Puerto Rico", 4),
        ("Bahamas", 3),
        ("Pakistán", 3),
        ("Bangladesh", 3),
        ("Sri Lanka", 3),
        ("Atenas", 4),
        ("Estambul", 4),
        ("El Cairo", 3),
        ("Abu Dabi", 3),
        ("Doha", 2),
        ("Riad", 2),
        ("Corea del Sur", 4),
        ("China", 5),
        ("Taiwán", 3),
        ("Siberia", 3),
        ("Groenlandia", 3),
        ("Islandia", 3),
        ("Bollywood", 3),
        ("Broadway", 3),
        ("Las Vegas", 4),
    ],
    "movies": [
        ("Star Wars", 5),
        ("Harry Potter", 5),
        ("Batman", 5),
        ("Titanic", 5),
        ("Matrix", 4),
        ("Toy Story", 5),
        ("Jurassic Park", 5),
        ("El Rey León", 5),
        ("Piratas del Caribe", 5),
        ("Indiana Jones", 4),
        ("Frozen", 5),
        ("Avatar", 5),
        ("Rocky", 4),
        ("James Bond", 5),
        ("Stranger Things", 4),
        ("Friends", 5),
        ("Breaking Bad", 4),
        ("Bob Esponja", 5),
        ("Gladiator", 4),
        ("Coco", 4),
        # Pair-only words
        ("Star Trek", 4),
        ("Guardians", 3),
        ("Dune", 3),
        ("Narnia", 4),
        ("Señor Anillos", 5),
        ("Percy Jackson", 3),
        ("Spider-Man", 5),
        ("Iron Man", 5),
        ("Superman", 5),
        ("Pearl Harbor", 3),
        ("Poseidón", 3),
        ("Naufrago", 4),
        ("Tron", 3),
        ("Inception", 4),
        ("Blade Runner", 3),
        ("Shrek", 5),
        ("Buscando a Nemo", 5),
        ("Monsters Inc", 4),
        ("King Kong", 4),
        ("Godzilla", 4),
        ("Rampage", 3),
        ("Bambi", 4),
        ("El Libro de la Selva", 4),
        ("Madagascar", 5),
        ("Peter Pan", 5),
        ("Moby Dick", 3),
        ("La Sirenita", 5),
        ("Lara Croft", 3),
        ("La Momia", 4),
        ("Uncharted", 3),
        ("Enredados", 4),
        ("Brave", 3),
        ("Moana", 4),
        ("Interstellar", 4),
        ("Gravity", 3),
        ("Prometheus", 3),
        ("Karate Kid", 4),
        ("Creed", 3),
        ("Raging Bull", 3),
        ("Mission Impossible", 4),
        ("Jason Bourne", 3),
        ("Kingsman", 3),
        ("Dark", 3),
        ("The OA", 2),
        ("Black Mirror", 4),
        ("Seinfeld", 3),
        ("How I Met", 4),
        ("The Big Bang", 4),
        ("Narcos", 4),
        ("Ozark", 3),
        ("Better Call Saul", 3),
        ("Doraemon", 4),
        ("Los Simpson", 5),
        ("Futurama", 4),
        ("Troya", 3),
        ("Espartaco", 3),
        ("300", 4),
        ("Soul", 4),
        ("Inside Out", 4),
        ("Up", 5),
    ],
    "music": [
        ("Guitarra", 5),
        ("Piano", 5),
        ("Batería", 5),
        ("Violín", 4),
        ("Flauta", 4),
        ("Trompeta", 4),
        ("Rock", 5),
        ("Reggaetón", 5),
        ("Jazz", 4),
        ("Rap", 5),
        ("Ópera", 3),
        ("DJ", 4),
        ("Concierto", 5),
        ("Salsa", 4),
        ("K-pop", 3),
        ("Arpa", 3),
        ("Saxofón", 3),
        ("Flamenco", 4),
        ("Sintetizador", 3),
        ("Karaoke", 4),
        # Pair-only words
        ("Ukulele", 3),
        ("Bajo", 4),
        ("Banjo", 3),
        ("Órgano", 3),
        ("Teclado", 5),
        ("Clavecín", 1),
        ("Bongos", 3),
        ("Tambor", 4),
        ("Cajón", 3),
        ("Viola", 2),
        ("Violonchelo", 3),
        ("Contrabajo", 3),
        ("Clarinete", 3),
        ("Oboe", 2),
        ("Piccolo", 2),
        ("Trombón", 3),
        ("Tuba", 3),
        ("Corneta", 3),
        ("Punk", 4),
        ("Metal", 4),
        ("Grunge", 3),
        ("Trap", 4),
        ("Dancehall", 2),
        ("Dembow", 2),
        ("Blues", 4),
        ("Swing", 3),
        ("Bossa nova", 2),
        ("Hip-hop", 5),
        ("Spoken word", 2),
        ("Musical", 4),
        ("Zarzuela", 2),
        ("Cabaret", 3),
        ("Productor", 4),
        ("MC", 3),
        ("VJ", 2),
        ("Festival", 5),
        ("Recital", 3),
        ("Gira", 4),
        ("Bachata", 4),
        ("Merengue", 4),
        ("Cumbia", 4),
        ("J-pop", 2),
        ("C-pop", 1),
        ("Eurovisión", 4),
        ("Lira", 2),
        ("Cítara", 1),
        ("Laúd", 2),
        ("Fagot", 2),
        ("Armónica", 3),
        ("Tango", 3),
        ("Samba", 3),
        ("Bolero", 3),
        ("Máquina de ritmos", 2),
        ("Theremin", 1),
        ("Sampler", 2),
        ("Coro", 4),
        ("Playback", 3),
        ("Dúo", 4),
    ],
    "science": [
        ("Robot", 4),
        ("Telescopio", 4),
        ("ADN", 3),
        ("Átomo", 4),
        ("Internet", 5),
        ("Cohete", 4),
        ("Dinosaurio", 5),
        ("Volcán", 4),
        ("Gravedad", 3),
        ("Láser", 3),
        ("Vacuna", 4),
        ("Algoritmo", 3),
        ("Galaxia", 4),
        ("Célula", 4),
        ("Reactor nuclear", 2),
        ("Inteligencia artificial", 4),
        ("Agujero negro", 3),
        ("Impresora 3D", 3),
        ("Clon", 3),
        ("Realidad virtual", 4),
        # Pair-only words
        ("Androide", 3),
        ("Dron", 4),
        ("Cyborg", 3),
        ("Microscopio", 3),
        ("Prismáticos", 3),
        ("Lupa", 4),
        ("ARN", 2),
        ("Gen", 3),
        ("Cromosoma", 3),
        ("Molécula", 3),
        ("Electrón", 3),
        ("Protón", 3),
        ("Intranet", 2),
        ("WiFi", 5),
        ("Bluetooth", 4),
        ("Satélite", 3),
        ("Transbordador", 3),
        ("Nave", 4),
        ("Fósil", 3),
        ("Meteorito", 3),
        ("Géiser", 2),
        ("Terremoto", 4),
        ("Tsunami", 4),
        ("Magnetismo", 3),
        ("Inercia", 2),
        ("Fricción", 3),
        ("Radar", 3),
        ("Sonar", 2),
        ("Rayos X", 3),
        ("Antibiótico", 3),
        ("Antídoto", 3),
        ("Suero", 3),
        ("Ecuación", 3),
        ("Fórmula", 4),
        ("Código", 5),
        ("Nebulosa", 2),
        ("Constelación", 3),
        ("Supernova", 3),
        ("Bacteria", 4),
        ("Virus", 5),
        ("Ameba", 3),
        ("Central eólica", 3),
        ("Placa solar", 3),
        ("Presa", 3),
        ("Machine learning", 3),
        ("Chatbot", 3),
        ("Red neuronal", 2),
        ("Estrella", 4),
        ("Quásar", 1),
        ("Púlsar", 1),
        ("Escáner", 4),
        ("CNC", 1),
        ("Cortadora láser", 2),
        ("Mutante", 3),
        ("Híbrido", 3),
        ("Transgénico", 2),
        ("Realidad aumentada", 3),
        ("Metaverso", 3),
        ("Simulador", 3),
    ],
    "emotions": [
        ("Alegría", 5),
        ("Tristeza", 5),
        ("Miedo", 5),
        ("Amor", 5),
        ("Rabia", 4),
        ("Sorpresa", 5),
        ("Envidia", 4),
        ("Orgullo", 4),
        ("Vergüenza", 4),
        ("Esperanza", 4),
        ("Aburrimiento", 4),
        ("Gratitud", 3),
        ("Soledad", 4),
        ("Valentía", 4),
        ("Culpa", 4),
        ("Paz", 5),
        ("Estrés", 5),
        ("Curiosidad", 4),
        ("Desprecio", 3),
        ("Éxtasis", 2),
        # Pair-only words
        ("Euforia", 3),
        ("Felicidad", 5),
        ("Entusiasmo", 4),
        ("Melancolía", 3),
        ("Nostalgia", 4),
        ("Pena", 5),
        ("Pánico", 4),
        ("Terror", 4),
        ("Ansiedad", 4),
        ("Cariño", 5),
        ("Pasión", 4),
        ("Ternura", 4),
        ("Furia", 3),
        ("Ira", 4),
        ("Frustración", 4),
        ("Asombro", 3),
        ("Estupor", 2),
        ("Incredulidad", 3),
        ("Celos", 4),
        ("Codicia", 3),
        ("Rivalidad", 4),
        ("Vanidad", 3),
        ("Soberbia", 3),
        ("Dignidad", 3),
        ("Timidez", 4),
        ("Pudor", 3),
        ("Humillación", 3),
        ("Ilusión", 4),
        ("Fe", 4),
        ("Optimismo", 4),
        ("Indiferencia", 3),
        ("Apatía", 3),
        ("Desgana", 3),
        ("Admiración", 3),
        ("Respeto", 4),
        ("Devoción", 3),
        ("Aislamiento", 3),
        ("Abandono", 4),
        ("Vacío", 3),
        ("Coraje", 3),
        ("Arrojo", 2),
        ("Osadía", 2),
        ("Remordimiento", 3),
        ("Arrepentimiento", 3),
        ("Pesar", 3),
        ("Serenidad", 3),
        ("Calma", 4),
        ("Tranquilidad", 4),
        ("Presión", 4),
        ("Tensión", 4),
        ("Agobio", 4),
        ("Intriga", 3),
        ("Interés", 4),
        ("Fascinación", 3),
        ("Desdén", 2),
        ("Rechazo", 4),
        ("Intolerancia", 3),
        ("Dicha", 3),
        ("Gozo", 3),
        ("Plenitud", 3),
    ],
}

# Semantic pairs from words.js + enriched with similarity & tier
# Each entry: (word_a, word_b, similarity, tier)
PAIRS_DATA = {
    "animals": [
        ("Perro", "Lobo", 0.88, "A"),
        ("Perro", "Gato", 0.72, "B"),
        ("Perro", "Zorro", 0.78, "B"),
        ("Gato", "Pantera", 0.75, "B"),
        ("Gato", "Lince", 0.72, "B"),
        ("Gato", "Tigre", 0.68, "C"),
        ("León", "Tigre", 0.92, "A"),
        ("León", "Puma", 0.88, "A"),
        ("León", "Leopardo", 0.87, "A"),
        ("Águila", "Halcón", 0.90, "A"),
        ("Águila", "Búho", 0.72, "B"),
        ("Águila", "Cóndor", 0.82, "B"),
        ("Tiburón", "Delfín", 0.72, "B"),
        ("Tiburón", "Orca", 0.78, "B"),
        ("Tiburón", "Ballena", 0.75, "B"),
        ("Elefante", "Rinoceronte", 0.78, "B"),
        ("Elefante", "Hipopótamo", 0.75, "B"),
        ("Elefante", "Mamut", 0.55, "C"),
        ("Serpiente", "Lagarto", 0.72, "B"),
        ("Serpiente", "Cocodrilo", 0.65, "C"),
        ("Serpiente", "Iguana", 0.68, "C"),
        ("Caballo", "Burro", 0.85, "A"),
        ("Caballo", "Cebra", 0.88, "A"),
        ("Caballo", "Poni", 0.92, "A"),
        ("Oso", "Panda", 0.78, "B"),
        ("Oso", "Koala", 0.60, "C"),
        ("Oso", "Mapache", 0.55, "C"),
        ("Mono", "Gorila", 0.85, "A"),
        ("Mono", "Chimpancé", 0.88, "A"),
        ("Mono", "Orangután", 0.82, "B"),
        ("Conejo", "Liebre", 0.90, "A"),
        ("Conejo", "Hámster", 0.68, "C"),
        ("Conejo", "Ratón", 0.62, "C"),
        ("Ballena", "Delfín", 0.78, "B"),
        ("Ballena", "Foca", 0.65, "C"),
        ("Ballena", "Morsa", 0.62, "C"),
        ("Pingüino", "Foca", 0.72, "B"),
        ("Pingüino", "Gaviota", 0.65, "C"),
        ("Pingüino", "Albatros", 0.68, "C"),
        ("Tortuga", "Caracol", 0.65, "C"),
        ("Tortuga", "Cangrejo", 0.58, "C"),
        ("Tortuga", "Lagarto", 0.72, "B"),
        ("Loro", "Tucán", 0.82, "B"),
        ("Loro", "Guacamayo", 0.92, "A"),
        ("Loro", "Canario", 0.75, "B"),
        ("Araña", "Escorpión", 0.72, "B"),
        ("Araña", "Hormiga", 0.65, "C"),
        ("Araña", "Escarabajo", 0.62, "C"),
        ("Mariposa", "Libélula", 0.78, "B"),
        ("Mariposa", "Abeja", 0.72, "B"),
        ("Mariposa", "Polilla", 0.90, "A"),
        ("Ciervo", "Alce", 0.88, "A"),
        ("Ciervo", "Reno", 0.85, "A"),
        ("Ciervo", "Gacela", 0.82, "B"),
        ("Ratón", "Rata", 0.92, "A"),
        ("Ratón", "Hámster", 0.78, "B"),
        ("Ratón", "Ardilla", 0.68, "C"),
        ("Jirafa", "Avestruz", 0.55, "C"),
        ("Jirafa", "Camello", 0.62, "C"),
        ("Jirafa", "Llama", 0.58, "C"),
    ],
    "food": [
        ("Pizza", "Calzone", 0.90, "A"),
        ("Pizza", "Focaccia", 0.75, "B"),
        ("Pizza", "Empanada", 0.68, "C"),
        ("Hamburguesa", "Hot Dog", 0.82, "B"),
        ("Hamburguesa", "Sándwich", 0.78, "B"),
        ("Hamburguesa", "Kebab", 0.68, "C"),
        ("Sushi", "Sashimi", 0.92, "A"),
        ("Sushi", "Tempura", 0.75, "B"),
        ("Sushi", "Ramen", 0.72, "B"),
        ("Paella", "Risotto", 0.82, "B"),
        ("Paella", "Arroz frito", 0.78, "B"),
        ("Paella", "Fideuá", 0.88, "A"),
        ("Chocolate", "Cacao", 0.88, "A"),
        ("Chocolate", "Brownie", 0.78, "B"),
        ("Chocolate", "Turrón", 0.72, "B"),
        ("Café", "Té", 0.78, "B"),
        ("Café", "Capuchino", 0.90, "A"),
        ("Café", "Espresso", 0.92, "A"),
        ("Cerveza", "Sidra", 0.82, "B"),
        ("Cerveza", "Vino", 0.72, "B"),
        ("Cerveza", "Limonada", 0.55, "C"),
        ("Helado", "Sorbete", 0.88, "A"),
        ("Helado", "Granizado", 0.78, "B"),
        ("Helado", "Natillas", 0.68, "C"),
        ("Tortilla", "Omelette", 0.92, "A"),
        ("Tortilla", "Frittata", 0.85, "A"),
        ("Tortilla", "Revuelto", 0.78, "B"),
        ("Croissant", "Donut", 0.75, "B"),
        ("Croissant", "Magdalena", 0.72, "B"),
        ("Croissant", "Churro", 0.70, "B"),
        ("Taco", "Burrito", 0.88, "A"),
        ("Taco", "Quesadilla", 0.82, "B"),
        ("Taco", "Enchilada", 0.85, "A"),
        ("Pasta", "Fideos", 0.90, "A"),
        ("Pasta", "Lasaña", 0.85, "A"),
        ("Pasta", "Macarrones", 0.92, "A"),
        ("Ensalada", "Gazpacho", 0.65, "C"),
        ("Ensalada", "Ceviche", 0.58, "C"),
        ("Ensalada", "Carpaccio", 0.55, "C"),
        ("Manzana", "Pera", 0.90, "A"),
        ("Manzana", "Melocotón", 0.82, "B"),
        ("Manzana", "Ciruela", 0.78, "B"),
        ("Queso", "Mantequilla", 0.78, "B"),
        ("Queso", "Yogur", 0.75, "B"),
        ("Queso", "Nata", 0.72, "B"),
        ("Pan", "Galleta", 0.72, "B"),
        ("Pan", "Tostada", 0.88, "A"),
        ("Pan", "Arepa", 0.78, "B"),
        ("Limonada", "Naranjada", 0.90, "A"),
        ("Limonada", "Zumo", 0.85, "A"),
        ("Limonada", "Horchata", 0.68, "C"),
        ("Fresa", "Frambuesa", 0.90, "A"),
        ("Fresa", "Cereza", 0.82, "B"),
        ("Fresa", "Mora", 0.85, "A"),
        ("Pollo", "Pavo", 0.85, "A"),
        ("Pollo", "Pato", 0.78, "B"),
        ("Pollo", "Codorniz", 0.72, "B"),
        ("Sopa", "Caldo", 0.90, "A"),
        ("Sopa", "Crema", 0.85, "A"),
        ("Sopa", "Guiso", 0.78, "B"),
    ],
    "sports": [
        ("Fútbol", "Rugby", 0.75, "B"),
        ("Fútbol", "Fútbol sala", 0.92, "A"),
        ("Fútbol", "Hockey", 0.72, "B"),
        ("Baloncesto", "Voleibol", 0.75, "B"),
        ("Baloncesto", "Balonmano", 0.78, "B"),
        ("Baloncesto", "Netball", 0.82, "B"),
        ("Tenis", "Bádminton", 0.82, "B"),
        ("Tenis", "Pádel", 0.88, "A"),
        ("Tenis", "Ping-pong", 0.85, "A"),
        ("Natación", "Waterpolo", 0.78, "B"),
        ("Natación", "Buceo", 0.75, "B"),
        ("Natación", "Surf", 0.68, "C"),
        ("Ciclismo", "Patinaje", 0.72, "B"),
        ("Ciclismo", "Monopatín", 0.65, "C"),
        ("Ciclismo", "BMX", 0.88, "A"),
        ("Boxeo", "Karate", 0.78, "B"),
        ("Boxeo", "Judo", 0.75, "B"),
        ("Boxeo", "Lucha libre", 0.82, "B"),
        ("Golf", "Billar", 0.58, "C"),
        ("Golf", "Croquet", 0.65, "C"),
        ("Golf", "Bolos", 0.55, "C"),
        ("Atletismo", "Maratón", 0.85, "A"),
        ("Atletismo", "Triatlón", 0.82, "B"),
        ("Atletismo", "Cross", 0.88, "A"),
        ("Esquí", "Snowboard", 0.90, "A"),
        ("Esquí", "Patinaje hielo", 0.78, "B"),
        ("Esquí", "Trineo", 0.72, "B"),
        ("Surf", "Windsurf", 0.88, "A"),
        ("Surf", "Kayak", 0.68, "C"),
        ("Surf", "Bodyboard", 0.90, "A"),
        ("Béisbol", "Softball", 0.92, "A"),
        ("Béisbol", "Cricket", 0.78, "B"),
        ("Béisbol", "Rounders", 0.82, "B"),
        ("Escalada", "Senderismo", 0.78, "B"),
        ("Escalada", "Rappel", 0.88, "A"),
        ("Escalada", "Espeleología", 0.72, "B"),
        ("Gimnasia", "Yoga", 0.78, "B"),
        ("Gimnasia", "Pilates", 0.82, "B"),
        ("Gimnasia", "Danza", 0.75, "B"),
        ("Esgrima", "Tiro con arco", 0.68, "C"),
        ("Esgrima", "Lanzamiento", 0.58, "C"),
        ("Esgrima", "Jabalina", 0.55, "C"),
        ("Ajedrez", "Damas", 0.88, "A"),
        ("Ajedrez", "Go", 0.82, "B"),
        ("Ajedrez", "Backgammon", 0.78, "B"),
        ("Fórmula 1", "Rally", 0.85, "A"),
        ("Fórmula 1", "NASCAR", 0.88, "A"),
        ("Fórmula 1", "MotoGP", 0.82, "B"),
        ("Skate", "Scooter", 0.78, "B"),
        ("Skate", "Roller", 0.82, "B"),
        ("Skate", "Longboard", 0.92, "A"),
        ("Polo", "Equitación", 0.82, "B"),
        ("Polo", "Hípica", 0.78, "B"),
        ("Polo", "Rodeo", 0.68, "C"),
        ("Rugby", "Fútbol americano", 0.88, "A"),
        ("Rugby", "Lacrosse", 0.72, "B"),
        ("Rugby", "Hurling", 0.65, "C"),
        ("Vela", "Remo", 0.75, "B"),
        ("Vela", "Piragüismo", 0.78, "B"),
        ("Vela", "Canoa", 0.72, "B"),
    ],
    "places": [
        ("París", "Londres", 0.82, "B"),
        ("París", "Roma", 0.85, "A"),
        ("París", "Berlín", 0.82, "B"),
        ("Tokio", "Seúl", 0.82, "B"),
        ("Tokio", "Pekín", 0.78, "B"),
        ("Tokio", "Osaka", 0.90, "A"),
        ("Nueva York", "Chicago", 0.82, "B"),
        ("Nueva York", "Los Ángeles", 0.78, "B"),
        ("Nueva York", "Toronto", 0.75, "B"),
        ("España", "Portugal", 0.90, "A"),
        ("España", "Italia", 0.85, "A"),
        ("España", "Francia", 0.82, "B"),
        ("Brasil", "Argentina", 0.85, "A"),
        ("Brasil", "Colombia", 0.78, "B"),
        ("Brasil", "México", 0.72, "B"),
        ("Egipto", "Marruecos", 0.78, "B"),
        ("Egipto", "Turquía", 0.72, "B"),
        ("Egipto", "Grecia", 0.68, "C"),
        ("Australia", "Nueva Zelanda", 0.90, "A"),
        ("Australia", "Canadá", 0.68, "C"),
        ("Australia", "Sudáfrica", 0.65, "C"),
        ("Moscú", "San Petersburgo", 0.88, "A"),
        ("Moscú", "Varsovia", 0.72, "B"),
        ("Moscú", "Praga", 0.68, "C"),
        ("Amazonas", "Nilo", 0.88, "A"),
        ("Amazonas", "Misisipi", 0.85, "A"),
        ("Amazonas", "Ganges", 0.82, "B"),
        ("Sahara", "Gobi", 0.90, "A"),
        ("Sahara", "Atacama", 0.88, "A"),
        ("Sahara", "Kalahari", 0.85, "A"),
        ("Alpes", "Andes", 0.90, "A"),
        ("Alpes", "Himalaya", 0.85, "A"),
        ("Alpes", "Pirineos", 0.88, "A"),
        ("Hawái", "Bali", 0.85, "A"),
        ("Hawái", "Maldivas", 0.82, "B"),
        ("Hawái", "Canarias", 0.78, "B"),
        ("Venecia", "Ámsterdam", 0.78, "B"),
        ("Venecia", "Brujas", 0.82, "B"),
        ("Venecia", "Estocolmo", 0.68, "C"),
        ("Cuba", "Jamaica", 0.88, "A"),
        ("Cuba", "Puerto Rico", 0.85, "A"),
        ("Cuba", "Bahamas", 0.82, "B"),
        ("India", "Pakistán", 0.82, "B"),
        ("India", "Bangladesh", 0.78, "B"),
        ("India", "Sri Lanka", 0.75, "B"),
        ("Roma", "Atenas", 0.85, "A"),
        ("Roma", "Estambul", 0.78, "B"),
        ("Roma", "El Cairo", 0.72, "B"),
        ("Dubái", "Abu Dabi", 0.92, "A"),
        ("Dubái", "Doha", 0.85, "A"),
        ("Dubái", "Riad", 0.78, "B"),
        ("Japón", "Corea del Sur", 0.82, "B"),
        ("Japón", "China", 0.75, "B"),
        ("Japón", "Taiwán", 0.78, "B"),
        ("Alaska", "Siberia", 0.85, "A"),
        ("Alaska", "Groenlandia", 0.82, "B"),
        ("Alaska", "Islandia", 0.78, "B"),
        ("Hollywood", "Bollywood", 0.88, "A"),
        ("Hollywood", "Broadway", 0.78, "B"),
        ("Hollywood", "Las Vegas", 0.72, "B"),
    ],
    "movies": [
        ("Star Wars", "Star Trek", 0.90, "A"),
        ("Star Wars", "Guardians", 0.72, "B"),
        ("Star Wars", "Dune", 0.78, "B"),
        ("Harry Potter", "Narnia", 0.82, "B"),
        ("Harry Potter", "Señor Anillos", 0.85, "A"),
        ("Harry Potter", "Percy Jackson", 0.82, "B"),
        ("Batman", "Spider-Man", 0.85, "A"),
        ("Batman", "Iron Man", 0.82, "B"),
        ("Batman", "Superman", 0.90, "A"),
        ("Titanic", "Pearl Harbor", 0.75, "B"),
        ("Titanic", "Poseidón", 0.72, "B"),
        ("Titanic", "Naufrago", 0.68, "C"),
        ("Matrix", "Tron", 0.78, "B"),
        ("Matrix", "Inception", 0.82, "B"),
        ("Matrix", "Blade Runner", 0.85, "A"),
        ("Toy Story", "Shrek", 0.78, "B"),
        ("Toy Story", "Buscando a Nemo", 0.85, "A"),
        ("Toy Story", "Monsters Inc", 0.88, "A"),
        ("Jurassic Park", "King Kong", 0.75, "B"),
        ("Jurassic Park", "Godzilla", 0.78, "B"),
        ("Jurassic Park", "Rampage", 0.72, "B"),
        ("El Rey León", "Bambi", 0.78, "B"),
        ("El Rey León", "El Libro de la Selva", 0.82, "B"),
        ("El Rey León", "Madagascar", 0.75, "B"),
        ("Piratas del Caribe", "Peter Pan", 0.68, "C"),
        ("Piratas del Caribe", "Moby Dick", 0.65, "C"),
        ("Piratas del Caribe", "La Sirenita", 0.62, "C"),
        ("Indiana Jones", "Lara Croft", 0.85, "A"),
        ("Indiana Jones", "La Momia", 0.82, "B"),
        ("Indiana Jones", "Uncharted", 0.88, "A"),
        ("Frozen", "Enredados", 0.88, "A"),
        ("Frozen", "Brave", 0.78, "B"),
        ("Frozen", "Moana", 0.82, "B"),
        ("Avatar", "Interstellar", 0.72, "B"),
        ("Avatar", "Gravity", 0.68, "C"),
        ("Avatar", "Prometheus", 0.72, "B"),
        ("Rocky", "Karate Kid", 0.82, "B"),
        ("Rocky", "Creed", 0.92, "A"),
        ("Rocky", "Raging Bull", 0.85, "A"),
        ("James Bond", "Mission Impossible", 0.88, "A"),
        ("James Bond", "Jason Bourne", 0.85, "A"),
        ("James Bond", "Kingsman", 0.78, "B"),
        ("Stranger Things", "Dark", 0.82, "B"),
        ("Stranger Things", "The OA", 0.72, "B"),
        ("Stranger Things", "Black Mirror", 0.75, "B"),
        ("Friends", "Seinfeld", 0.85, "A"),
        ("Friends", "How I Met", 0.88, "A"),
        ("Friends", "The Big Bang", 0.82, "B"),
        ("Breaking Bad", "Narcos", 0.78, "B"),
        ("Breaking Bad", "Ozark", 0.82, "B"),
        ("Breaking Bad", "Better Call Saul", 0.92, "A"),
        ("Bob Esponja", "Doraemon", 0.78, "B"),
        ("Bob Esponja", "Los Simpson", 0.82, "B"),
        ("Bob Esponja", "Futurama", 0.78, "B"),
        ("Gladiator", "Troya", 0.88, "A"),
        ("Gladiator", "Espartaco", 0.90, "A"),
        ("Gladiator", "300", 0.85, "A"),
        ("Coco", "Soul", 0.88, "A"),
        ("Coco", "Inside Out", 0.82, "B"),
        ("Coco", "Up", 0.78, "B"),
    ],
    "music": [
        ("Guitarra", "Ukulele", 0.88, "A"),
        ("Guitarra", "Bajo", 0.82, "B"),
        ("Guitarra", "Banjo", 0.78, "B"),
        ("Piano", "Órgano", 0.85, "A"),
        ("Piano", "Teclado", 0.88, "A"),
        ("Piano", "Clavecín", 0.82, "B"),
        ("Batería", "Bongos", 0.82, "B"),
        ("Batería", "Tambor", 0.88, "A"),
        ("Batería", "Cajón", 0.78, "B"),
        ("Violín", "Viola", 0.92, "A"),
        ("Violín", "Violonchelo", 0.88, "A"),
        ("Violín", "Contrabajo", 0.78, "B"),
        ("Flauta", "Clarinete", 0.82, "B"),
        ("Flauta", "Oboe", 0.85, "A"),
        ("Flauta", "Piccolo", 0.90, "A"),
        ("Trompeta", "Trombón", 0.85, "A"),
        ("Trompeta", "Tuba", 0.78, "B"),
        ("Trompeta", "Corneta", 0.90, "A"),
        ("Rock", "Punk", 0.85, "A"),
        ("Rock", "Metal", 0.88, "A"),
        ("Rock", "Grunge", 0.85, "A"),
        ("Reggaetón", "Trap", 0.82, "B"),
        ("Reggaetón", "Dancehall", 0.75, "B"),
        ("Reggaetón", "Dembow", 0.88, "A"),
        ("Jazz", "Blues", 0.88, "A"),
        ("Jazz", "Swing", 0.82, "B"),
        ("Jazz", "Bossa nova", 0.78, "B"),
        ("Rap", "Hip-hop", 0.92, "A"),
        ("Rap", "Trap", 0.82, "B"),
        ("Rap", "Spoken word", 0.72, "B"),
        ("Ópera", "Musical", 0.78, "B"),
        ("Ópera", "Zarzuela", 0.88, "A"),
        ("Ópera", "Cabaret", 0.68, "C"),
        ("DJ", "Productor", 0.78, "B"),
        ("DJ", "MC", 0.75, "B"),
        ("DJ", "VJ", 0.85, "A"),
        ("Concierto", "Festival", 0.85, "A"),
        ("Concierto", "Recital", 0.88, "A"),
        ("Concierto", "Gira", 0.78, "B"),
        ("Salsa", "Bachata", 0.88, "A"),
        ("Salsa", "Merengue", 0.85, "A"),
        ("Salsa", "Cumbia", 0.82, "B"),
        ("K-pop", "J-pop", 0.92, "A"),
        ("K-pop", "C-pop", 0.88, "A"),
        ("K-pop", "Eurovisión", 0.62, "C"),
        ("Arpa", "Lira", 0.88, "A"),
        ("Arpa", "Cítara", 0.82, "B"),
        ("Arpa", "Laúd", 0.78, "B"),
        ("Saxofón", "Clarinete", 0.82, "B"),
        ("Saxofón", "Fagot", 0.72, "B"),
        ("Saxofón", "Armónica", 0.65, "C"),
        ("Flamenco", "Tango", 0.78, "B"),
        ("Flamenco", "Samba", 0.72, "B"),
        ("Flamenco", "Bolero", 0.75, "B"),
        ("Sintetizador", "Máquina de ritmos", 0.85, "A"),
        ("Sintetizador", "Theremin", 0.78, "B"),
        ("Sintetizador", "Sampler", 0.82, "B"),
        ("Karaoke", "Coro", 0.68, "C"),
        ("Karaoke", "Playback", 0.82, "B"),
        ("Karaoke", "Dúo", 0.65, "C"),
    ],
    "science": [
        ("Robot", "Androide", 0.92, "A"),
        ("Robot", "Dron", 0.68, "C"),
        ("Robot", "Cyborg", 0.88, "A"),
        ("Telescopio", "Microscopio", 0.85, "A"),
        ("Telescopio", "Prismáticos", 0.82, "B"),
        ("Telescopio", "Lupa", 0.72, "B"),
        ("ADN", "ARN", 0.92, "A"),
        ("ADN", "Gen", 0.85, "A"),
        ("ADN", "Cromosoma", 0.82, "B"),
        ("Átomo", "Molécula", 0.85, "A"),
        ("Átomo", "Electrón", 0.82, "B"),
        ("Átomo", "Protón", 0.82, "B"),
        ("Internet", "Intranet", 0.88, "A"),
        ("Internet", "WiFi", 0.82, "B"),
        ("Internet", "Bluetooth", 0.72, "B"),
        ("Cohete", "Satélite", 0.78, "B"),
        ("Cohete", "Transbordador", 0.88, "A"),
        ("Cohete", "Nave", 0.85, "A"),
        ("Dinosaurio", "Mamut", 0.72, "B"),
        ("Dinosaurio", "Fósil", 0.78, "B"),
        ("Dinosaurio", "Meteorito", 0.62, "C"),
        ("Volcán", "Géiser", 0.82, "B"),
        ("Volcán", "Terremoto", 0.78, "B"),
        ("Volcán", "Tsunami", 0.72, "B"),
        ("Gravedad", "Magnetismo", 0.75, "B"),
        ("Gravedad", "Inercia", 0.82, "B"),
        ("Gravedad", "Fricción", 0.72, "B"),
        ("Láser", "Radar", 0.78, "B"),
        ("Láser", "Sonar", 0.72, "B"),
        ("Láser", "Rayos X", 0.75, "B"),
        ("Vacuna", "Antibiótico", 0.82, "B"),
        ("Vacuna", "Antídoto", 0.78, "B"),
        ("Vacuna", "Suero", 0.75, "B"),
        ("Algoritmo", "Ecuación", 0.78, "B"),
        ("Algoritmo", "Fórmula", 0.82, "B"),
        ("Algoritmo", "Código", 0.85, "A"),
        ("Galaxia", "Nebulosa", 0.82, "B"),
        ("Galaxia", "Constelación", 0.78, "B"),
        ("Galaxia", "Supernova", 0.75, "B"),
        ("Célula", "Bacteria", 0.78, "B"),
        ("Célula", "Virus", 0.72, "B"),
        ("Célula", "Ameba", 0.82, "B"),
        ("Reactor nuclear", "Central eólica", 0.78, "B"),
        ("Reactor nuclear", "Placa solar", 0.75, "B"),
        ("Reactor nuclear", "Presa", 0.68, "C"),
        ("Inteligencia artificial", "Machine learning", 0.90, "A"),
        ("Inteligencia artificial", "Chatbot", 0.78, "B"),
        ("Inteligencia artificial", "Red neuronal", 0.85, "A"),
        ("Agujero negro", "Estrella", 0.72, "B"),
        ("Agujero negro", "Quásar", 0.85, "A"),
        ("Agujero negro", "Púlsar", 0.82, "B"),
        ("Impresora 3D", "Escáner", 0.72, "B"),
        ("Impresora 3D", "CNC", 0.82, "B"),
        ("Impresora 3D", "Cortadora láser", 0.85, "A"),
        ("Clon", "Mutante", 0.78, "B"),
        ("Clon", "Híbrido", 0.75, "B"),
        ("Clon", "Transgénico", 0.82, "B"),
        ("Realidad virtual", "Realidad aumentada", 0.92, "A"),
        ("Realidad virtual", "Metaverso", 0.85, "A"),
        ("Realidad virtual", "Simulador", 0.82, "B"),
    ],
    "emotions": [
        ("Alegría", "Euforia", 0.88, "A"),
        ("Alegría", "Felicidad", 0.92, "A"),
        ("Alegría", "Entusiasmo", 0.82, "B"),
        ("Tristeza", "Melancolía", 0.88, "A"),
        ("Tristeza", "Nostalgia", 0.82, "B"),
        ("Tristeza", "Pena", 0.90, "A"),
        ("Miedo", "Pánico", 0.88, "A"),
        ("Miedo", "Terror", 0.85, "A"),
        ("Miedo", "Ansiedad", 0.82, "B"),
        ("Amor", "Cariño", 0.88, "A"),
        ("Amor", "Pasión", 0.82, "B"),
        ("Amor", "Ternura", 0.85, "A"),
        ("Rabia", "Furia", 0.92, "A"),
        ("Rabia", "Ira", 0.90, "A"),
        ("Rabia", "Frustración", 0.78, "B"),
        ("Sorpresa", "Asombro", 0.90, "A"),
        ("Sorpresa", "Estupor", 0.82, "B"),
        ("Sorpresa", "Incredulidad", 0.78, "B"),
        ("Envidia", "Celos", 0.88, "A"),
        ("Envidia", "Codicia", 0.78, "B"),
        ("Envidia", "Rivalidad", 0.68, "C"),
        ("Orgullo", "Vanidad", 0.82, "B"),
        ("Orgullo", "Soberbia", 0.85, "A"),
        ("Orgullo", "Dignidad", 0.72, "B"),
        ("Vergüenza", "Timidez", 0.82, "B"),
        ("Vergüenza", "Pudor", 0.85, "A"),
        ("Vergüenza", "Humillación", 0.78, "B"),
        ("Esperanza", "Ilusión", 0.85, "A"),
        ("Esperanza", "Fe", 0.82, "B"),
        ("Esperanza", "Optimismo", 0.88, "A"),
        ("Aburrimiento", "Indiferencia", 0.78, "B"),
        ("Aburrimiento", "Apatía", 0.85, "A"),
        ("Aburrimiento", "Desgana", 0.82, "B"),
        ("Gratitud", "Admiración", 0.78, "B"),
        ("Gratitud", "Respeto", 0.75, "B"),
        ("Gratitud", "Devoción", 0.72, "B"),
        ("Soledad", "Aislamiento", 0.88, "A"),
        ("Soledad", "Abandono", 0.82, "B"),
        ("Soledad", "Vacío", 0.78, "B"),
        ("Valentía", "Coraje", 0.92, "A"),
        ("Valentía", "Arrojo", 0.85, "A"),
        ("Valentía", "Osadía", 0.82, "B"),
        ("Culpa", "Remordimiento", 0.90, "A"),
        ("Culpa", "Arrepentimiento", 0.88, "A"),
        ("Culpa", "Pesar", 0.82, "B"),
        ("Paz", "Serenidad", 0.90, "A"),
        ("Paz", "Calma", 0.88, "A"),
        ("Paz", "Tranquilidad", 0.92, "A"),
        ("Estrés", "Presión", 0.85, "A"),
        ("Estrés", "Tensión", 0.88, "A"),
        ("Estrés", "Agobio", 0.85, "A"),
        ("Curiosidad", "Intriga", 0.82, "B"),
        ("Curiosidad", "Interés", 0.85, "A"),
        ("Curiosidad", "Fascinación", 0.82, "B"),
        ("Desprecio", "Desdén", 0.90, "A"),
        ("Desprecio", "Rechazo", 0.78, "B"),
        ("Desprecio", "Intolerancia", 0.72, "B"),
        ("Éxtasis", "Dicha", 0.85, "A"),
        ("Éxtasis", "Gozo", 0.88, "A"),
        ("Éxtasis", "Plenitud", 0.82, "B"),
    ],
}


def build_pack():
    pack = {
        "pack_meta": {
            "pack_id": "base_v1",
            "name": "Pack Base — El Impostor",
            "version": 1,
            "language": "es",
            "is_free": True,
        },
        "categories": CATEGORIES,
        "words": [],
        "semantic_pairs": [],
    }

    for cat in CATEGORIES:
        cid = cat["id"]
        if cid not in WORDS_DATA:
            continue
        for text, diff in WORDS_DATA[cid]:
            pack["words"].append(
                {"text": text, "category": cat["name"], "difficulty": diff}
            )

    for cat in CATEGORIES:
        cid = cat["id"]
        if cid not in PAIRS_DATA:
            continue
        for a, b, sim, tier in PAIRS_DATA[cid]:
            pack["semantic_pairs"].append(
                {"word_a": a, "word_b": b, "similarity": sim, "tier": tier}
            )

    # Summary
    total_w = len(pack["words"])
    total_p = len(pack["semantic_pairs"])
    tier_a = sum(1 for p in pack["semantic_pairs"] if p["tier"] == "A")
    tier_b = sum(1 for p in pack["semantic_pairs"] if p["tier"] == "B")
    tier_c = sum(1 for p in pack["semantic_pairs"] if p["tier"] == "C")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(pack, f, ensure_ascii=False, indent=2)

    size_kb = os.path.getsize(OUT) / 1024
    print(f"[✓] Base pack generado: {OUT}")
    print(f"    Categorías: {len(pack['categories'])}")
    print(f"    Palabras:   {total_w}")
    print(f"    Pares:      {total_p} (A:{tier_a} B:{tier_b} C:{tier_c})")
    print(f"    Tamaño:     {size_kb:.1f} KB")


if __name__ == "__main__":
    build_pack()
